//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Higgs.Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action name is not found in route value dictionary..
        /// </summary>
        internal static string ActionNameIsNotFoundInRouteValueDictionary {
            get {
                return ResourceManager.GetString("ActionNameIsNotFoundInRouteValueDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controll name is not found in route value dictionary..
        /// </summary>
        internal static string ControllerNameIsNotFoundInRouteValueDictionary {
            get {
                return ResourceManager.GetString("ControllerNameIsNotFoundInRouteValueDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default resource file is not found..
        /// </summary>
        internal static string DefaultResourceFileNotFound {
            get {
                return ResourceManager.GetString("DefaultResourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your entered expression is not {0} type. You enter {1} type..
        /// </summary>
        internal static string ExpressionTypeIsNotEqual {
            get {
                return ResourceManager.GetString("ExpressionTypeIsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binded property is member expression like TModel.Property1 where TModel is type to be binded..
        /// </summary>
        internal static string InvalidBindedPropertyException {
            get {
                return ResourceManager.GetString("InvalidBindedPropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default home view is not defined..
        /// </summary>
        internal static string NullDefaultHomeView {
            get {
                return ResourceManager.GetString("NullDefaultHomeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default LogOn view is null. Please specify only one method in one controller class by using DefaultView Attribute..
        /// </summary>
        internal static string NullDefaultLogOnView {
            get {
                return ResourceManager.GetString("NullDefaultLogOnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object constructor argument should be a direct member..
        /// </summary>
        internal static string ParameterTypeInNewExpressionIsInvalid {
            get {
                return ResourceManager.GetString("ParameterTypeInNewExpressionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource directory of {0} is not found..
        /// </summary>
        internal static string ResourceDirectoryNotFound {
            get {
                return ResourceManager.GetString("ResourceDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory derive from IStaticFileController interface..
        /// </summary>
        internal static string StaticFileControllerFactory_IsNotAssignableFromIStaticFileController {
            get {
                return ResourceManager.GetString("StaticFileControllerFactory_IsNotAssignableFromIStaticFileController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting time must greater than 0..
        /// </summary>
        internal static string WaitingTimeMustGreaterThanZero {
            get {
                return ResourceManager.GetString("WaitingTimeMustGreaterThanZero", resourceCulture);
            }
        }
    }
}
